apiVersion: v1
kind: Pod
metadata: 
  name: morevol2
spec:
  containers:
  - name: centos
    image: centos:7
    command:
    - sleep
    - "3600"
    volumeMounts:
      - mountPath: /centos
        name: test
  - name: centos
    image: centos:7
    command:
    - sleep
    - "3600"
    volumeMounts:
      - mountPath: /centos2
        name: test
  volumes: 
    - name: test
      emptyDir: {}
